name: Android CI

on:
  push:
    branches: [ "main" ]
    # 添加 tag 触发条件
    tags:
      - 'v*'  # 匹配所有以 v 开头的标签，如 v1.0.0
  pull_request:
    branches: [ "main" ]
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew :composeApp:assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: composeApp/build/outputs/apk/debug/composeApp-debug.apk

    # 修改 Release 创建条件，支持 tag 触发
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')  # 当是 tag 推送时创建 release
      uses: softprops/action-gh-release@v1
      with:
        files: composeApp/build/outputs/apk/debug/composeApp-debug.apk
        name: Release ${{ github.ref_name }}  # 使用 tag 名称作为 release 名称
        body: |
          Release ${{ github.ref_name }}
          
          构建时间: ${{ github.event.head_commit.timestamp }}
          Commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}